# Generated by Django 6.0.1 on 2026-02-02 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(
                    choices=[(1, '1 Mo'), (2, '2 Mo'), (3, '3 Mo'), (4, '4 Mo'), (6, '6 Mo'), (12, '1 Yr'),
                             (24, '2 Yr'), (36, '3 Yr'), (60, '5 Yr'), (84, '7 Yr'), (120, '10 Yr'), (240, '20 Yr'),
                             (360, '30 Yr')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
